version: "3.7"

services:
  postgresdb:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=suuser
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    ports:
      - "5432:5432"

  user_backend:
    build:
      context: ./user_backend
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    environment:
      - POSTGRES_DB_HOST=postgresdb
    depends_on:
      - postgresdb

  book_backend:
    build:
      context: ./book_backend
      dockerfile: Dockerfile
    ports:
      - "1235:1235"
    environment:
      - POSTGRES_DB_HOST=postgresdb
    depends_on:
      - postgresdb

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - user_backend